"""Add email to User

Revision ID: 03746878b4fb
Revises: 725cad9db75b
Create Date: 2024-06-18 02:36:30.863239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03746878b4fb'
down_revision = '725cad9db75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('signature',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('signature',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=45),
               nullable=True)

    # ### end Alembic commands ###
