"""Add Delivery model and update User model for roles

Revision ID: 42662d7bda1c
Revises: 74ab405d6e9f
Create Date: 2024-10-16 23:22:26.268605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42662d7bda1c'
down_revision = '74ab405d6e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('items_delivered', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery')
    # ### end Alembic commands ###
