"""Migración inicial

Revision ID: 44e9405c98dd
Revises: 
Create Date: 2024-10-17 17:10:18.493998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44e9405c98dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('dia_reparto', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente_reparto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=200), nullable=False),
    sa.Column('reparto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reparto', sa.Date(), nullable=False),
    sa.Column('items_entregados', sa.String(length=500), nullable=False),
    sa.Column('estado_pago', sa.String(length=1), nullable=True),
    sa.Column('comprobante', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comment')
    op.drop_table('delivery')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('message_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('signature', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='message_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('delivery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('items_delivered', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='delivery_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='delivery_pkey')
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='comment_message_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='comment_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey')
    )
    op.drop_table('cliente_reparto')
    op.drop_table('reparto')
    # ### end Alembic commands ###
