"""Add User model

Revision ID: 525a4fbfcecb
Revises: d3e7bb8b09c3
Create Date: 2024-06-17 13:53:08.847865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525a4fbfcecb'
down_revision = 'd3e7bb8b09c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
