"""Inicializar migraciones desde cero

Revision ID: 5512a75d7bf8
Revises: 
Create Date: 2024-10-21 00:34:06.104495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5512a75d7bf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('items_delivered', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cliente_reparto')
    op.drop_table('reparto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparto',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reparto_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('empleado_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dia_reparto', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['user.id'], name='reparto_empleado_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reparto_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cliente_reparto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_cliente', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('reparto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_reparto', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('items_entregados', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('estado_pago', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('comprobante', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparto.id'], name='cliente_reparto_reparto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cliente_reparto_pkey')
    )
    op.drop_table('comment')
    op.drop_table('message')
    op.drop_table('delivery')
    # ### end Alembic commands ###
